server:
  port: 8762 # 端口

spring:
  application:
    name: eureka-server

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka-server01			  # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://localhost:8761/eureka/

